# Generated by Django 5.0.3 on 2024-05-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_Dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
