# Generated by Django 5.0.3 on 2024-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_link',
            field=models.CharField(blank=True, max_length=765),
        ),
    ]
