# Generated by Django 5.0.3 on 2024-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_p_dosage_product_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_Dosage_Strength',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
