# Generated by Django 5.0.3 on 2025-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product_p_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
