# Generated by Django 5.0.3 on 2025-06-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_product_stock_product_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
