# Generated by Django 5.0.3 on 2025-03-27 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('division', 'Division'), ('zilla', 'Zilla'), ('upazila', 'Upazila'), ('union', 'Union')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='custom_admin.location')),
            ],
            options={
                'unique_together': {('name', 'level', 'parent')},
            },
        ),
    ]
