# Generated by Django 5.0.3 on 2025-04-27 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_location_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=20)),
                ('ordered_products', models.TextField()),
                ('total', models.FloatField()),
                ('del_adress', models.TextField(blank=True, null=True)),
                ('payment_options', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('TxID', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('prescriptions', models.JSONField(blank=True, null=True)),
                ('Delivery_status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
