# Generated by Django 5.0.3 on 2025-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_temporaryorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryorders',
            name='for_stock',
            field=models.TextField(default='null'),
        ),
    ]
