# Generated by Django 5.0.3 on 2025-03-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presciption_order',
            name='payment_options',
            field=models.CharField(blank=True, default='cod', max_length=20),
        ),
    ]
