# Generated by Django 5.0.3 on 2025-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_product',
            name='feature',
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_image',
            field=models.ImageField(default='static/cat-icons/syringe.png', upload_to='media/'),
        ),
    ]
