# Generated by Django 5.0.3 on 2024-07-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_product',
            old_name='sku',
            new_name='product_code',
        ),
    ]
