# Generated by Django 5.0.3 on 2024-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='p_Dosage_Strength',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
