# Generated by Django 4.2.3 on 2024-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='add_to_list',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_options',
            field=models.CharField(blank=True, default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='prescriptions',
            field=models.JSONField(blank=True, default='null'),
        ),
    ]
