# Generated by Django 4.2.3 on 2024-04-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_main_product_add_to_list_orders_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='inventory_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='main_product',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='main_product',
            name='sku',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Contradictions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Indications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Interaction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Pharmacology',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Pregnancy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Side_Effects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Storage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_Therapeutic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_generics',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
