# Generated by Django 5.0.3 on 2024-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sku_main_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='p_category',
            field=models.CharField(choices=[('General Health', 'General Health'), ('Cold & Allergies Remedies', 'Cold & Allergies Remedies'), ('Heart Health', 'Heart Health'), ('Diabetes Care', 'Diabetes Care'), ('Lungs & Respiratory Health', 'Lungs & Respiratory Health'), ('Brain & Neurological Health', 'Brain & Neurological Health'), ('Muscles & Bone Health', 'Muscles & Bone Health'), ('Digestive Health', 'Digestive Health'), ('Medical Devices', 'Medical Devices'), ('Sexual Health', 'Sexual Health'), ('Women Health', 'Women Health'), ('Infant care', 'Infant care'), ('Supplements & Nutrition', 'Supplements & Nutrition'), ('Personal Health', 'Personal Health'), ('Blood and Circulatory Health', 'Blood and Circulatory Health'), ('Mental Health', 'Mental Health'), ('Kidney and Renal Health', 'Kidney and Renal Health'), ('Infection Management', 'Infection Management'), ('Immune System Health', 'Immune System Health'), ('Liver Health', 'Liver Health'), ('Thyroids and Hormones', 'Thyroids and Hormones'), ('Physical Injury', 'Physical Injury'), ('Pain Relief', 'Pain Relief')], max_length=255),
        ),
    ]
