# Generated by Django 5.0.3 on 2024-03-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_presciption_order_txid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='add_to_list',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=255),
        ),
    ]
