# Generated by Django 5.0.3 on 2024-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_main_product_add_to_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_options',
            field=models.CharField(blank=True, default='cod', max_length=20),
        ),
    ]
