# Generated by Django 5.0.3 on 2025-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_main_product_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='Model',
            field=models.TextField(blank=True),
        ),
    ]
