# Generated by Django 5.0.3 on 2025-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_main_product_p_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='m_or_p',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
