# Generated by Django 5.0.3 on 2025-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_main_product_description_main_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_image',
            field=models.ImageField(default='static/cat-icons/syringe.png', upload_to='media/'),
        ),
    ]
