# Generated by Django 5.0.3 on 2025-01-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_main_product_m_or_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='m_or_p',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
