# Generated by Django 5.0.3 on 2025-03-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_main_product_batch_main_product_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='p_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
