# Generated by Django 5.0.3 on 2025-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_main_product_count_alter_main_product_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='sl',
            field=models.IntegerField(default=1),
        ),
    ]
