# Generated by Django 5.0.3 on 2025-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_main_product_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='parent_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='main_product',
            name='sl_count',
            field=models.IntegerField(default=1),
        ),
    ]
