# Generated by Django 5.0.3 on 2025-03-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_main_product_alert_alter_main_product_p_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_product',
            name='alert',
        ),
    ]
