# Generated by Django 5.0.3 on 2025-04-27 18:54

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orders_for_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='bundling',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Box', 'Box'), ('Pack', 'Pack'), ('Piece', 'Piece')], max_length=14),
        ),
        migrations.AddField(
            model_name='main_product',
            name='stripPerBox',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
