# Generated by Django 5.0.3 on 2025-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_main_product_bundling_main_product_stripperbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='bundling',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
